# Generated by Django 3.2.4 on 2021-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the book's natural language (e.g. English, French, Korean, etc.)", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
